---
- name: perform optional versionscheck
  ansible.builtin.include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: Gather variables for each operating system
  ansible.builtin.include_vars: "{{ lookup('first_found', gitea_variables) }}"

- name: "Check gitea version"
  ansible.builtin.shell: "set -eo pipefail; /usr/local/bin/gitea -v | cut -d' ' -f 3"
  args:
    executable: /bin/bash
  register: gitea_active_version
  changed_when: false
  failed_when: false
  when: gitea_version_check|bool

- name: backup gitea before update
  ansible.builtin.include_tasks: backup.yml
  when: gitea_backup_on_upgrade|bool

- name: create gitea user and role
  ansible.builtin.include_tasks: create_user.yml

- name: install or update gitea
  ansible.builtin.include_tasks: install.yml

- name: Create directorys
  ansible.builtin.include_tasks: directory.yml

- include: install_systemd.yml
  when: ansible_service_mgr == "systemd"

- include_tasks: jwt_secrets.yml

- include_tasks: gitea_secrets.yml

- name: "Configure gitea"
  template:
    src: gitea.ini.j2
    dest: /etc/gitea/gitea.ini
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: 0600
  notify: "Restart gitea"

- name: "Service gitea"
  service:
    name: gitea
    state: started
    enabled: true
  when: ansible_service_mgr == "systemd"

- include: fail2ban.yml
  when: gitea_fail2ban_enabled|bool
